In [22]:
import numpy as np 
import pandas as pd 
import os 
import matplotlib.pyplot as plt
import seaborn as sns


In [23]:
# import data 
df = pd.read_csv("C:/KMUTNB/Project_own/python/Project/hand_sign_classification/dataset_hand.csv",index_col = False)
df.sample(10)


X_0       Y_0       X_1       Y_1       X_2       Y_2       X_3  \
1052  0.255110  0.830530  0.461430  0.809147  0.642489  0.692301  0.754852   
247   0.782684  0.803285  0.819248  0.628246  0.684931  0.420724  0.578046   
764   0.265988  0.849949  0.476580  0.820168  0.651561  0.732221  0.779198   
1092  0.281758  0.835933  0.470560  0.806338  0.642824  0.686799  0.749629   
657   0.294429  0.796139  0.484854  0.781119  0.644415  0.708460  0.751598   
986   0.278704  0.822343  0.472415  0.793045  0.641837  0.682188  0.746363   
768   0.274831  0.844964  0.488215  0.815352  0.665709  0.730300  0.791491   
835   0.292295  0.843319  0.490859  0.810748  0.651589  0.718811  0.774701   
166   0.810269  0.737387  0.773490  0.560674  0.610993  0.381284  0.479447   
992   0.277257  0.810698  0.467712  0.791969  0.642727  0.680476  0.746788   

           Y_3       X_4       Y_4  ...      Y_16      X_17      Y_17  \
1052  0.568314  0.855881  0.500625  ...  0.574508  0.210378  0.474088   
247   0.275891  0.552776  0.165443  ...  0.744395  0.235492  0.820101   
764   0.663062  0.844759  0.584522  ...  0.127721  0.207218  0.494904   
1092  0.563803  0.850044  0.499785  ...  0.599390  0.221046  0.480055   
657   0.626785  0.811011  0.549501  ...  0.165456  0.266035  0.469423   
986   0.569591  0.842921  0.508932  ...  0.580710  0.231233  0.482513   
768   0.658289  0.860821  0.580203  ...  0.124951  0.207933  0.493539   
835   0.652338  0.846986  0.578062  ...  0.130127  0.224714  0.502719   
166   0.270980  0.413563  0.175358  ...  0.694772  0.369454  0.816876   
992   0.567564  0.839502  0.508213  ...  0.572685  0.233523  0.481275   

          X_18      Y_18      X_19      Y_19      X_20      Y_20  Label  
1052  0.196753  0.346295  0.179642  0.270679  0.173026  0.188532      3  
247   0.248434  0.803275  0.405957  0.812574  0.472187  0.812190      0  
764   0.199831  0.371022  0.226509  0.287186  0.272026  0.216541      2  
1092  0.204084  0.356775  0.185598  0.284751  0.175592  0.204701      3  
657   0.246281  0.365126  0.259111  0.299020  0.294074  0.248358      2  
986   0.218442  0.352151  0.206556  0.283561  0.207018  0.201602      3  
768   0.196664  0.369598  0.221590  0.288889  0.265008  0.220307      2  
835   0.195577  0.384647  0.205837  0.298638  0.236382  0.225261      2  
166   0.282938  0.791699  0.415168  0.769098  0.507246  0.761564      0  
992   0.222256  0.357978  0.210027  0.290662  0.209858  0.213164      3  

[10 rows x 43 columns]

In [24]:
# Check missing data
missing_data = df.isnull().sum()
print(missing_data)
df.info()

X_0      0
Y_0      0
X_1      0
Y_1      0
X_2      0
Y_2      0
X_3      0
Y_3      0
X_4      0
Y_4      0
X_5      0
Y_5      0
X_6      0
Y_6      0
X_7      0
Y_7      0
X_8      0
Y_8      0
X_9      0
Y_9      0
X_10     0
Y_10     0
X_11     0
Y_11     0
X_12     0
Y_12     0
X_13     0
Y_13     0
X_14     0
Y_14     0
X_15     0
Y_15     0
X_16     0
Y_16     0
X_17     0
Y_17     0
X_18     0
Y_18     0
X_19     0
Y_19     0
X_20     0
Y_20     0
Label    0
dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1505 entries, 0 to 1504
Data columns (total 43 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   X_0     1505 non-null   float64
 1   Y_0     1505 non-null   float64
 2   X_1     1505 non-null   float64
 3   Y_1     1505 non-null   float64
 4   X_2     1505 non-null   float64
 5   Y_2     1505 non-null   float64
 6   X_3     1505 non-null   float64
 7   Y_3     1505 non-null   float64
 8   X_4     1505 non-null   float64


In [25]:
# Prepare data before train model
#import ast
#df["Landmark_Hand"] = df["Landmark_Hand"]
#df["Landmark_Hand"] = df["Landmark_Hand"].apply(lambda x: ast.literal_eval(x))

X = df.drop(["Label"],axis=1)

#X = np.asarray(df.drop(["Label"],axis=1))
y = df["Label"]
X


X_0       Y_0       X_1       Y_1       X_2       Y_2       X_3  \
0     0.806679  0.780557  0.804999  0.597826  0.663066  0.396792  0.537669   
1     0.805065  0.773556  0.802015  0.596905  0.656308  0.404338  0.533218   
2     0.806179  0.778639  0.797370  0.592600  0.653145  0.397820  0.533523   
3     0.791172  0.804925  0.831388  0.626491  0.706023  0.413008  0.598448   
4     0.781778  0.812453  0.826525  0.635463  0.721443  0.414198  0.609732   
...        ...       ...       ...       ...       ...       ...       ...   
1500  0.391563  0.850573  0.574135  0.782322  0.695630  0.660801  0.768174   
1501  0.395044  0.849404  0.572205  0.782069  0.690668  0.662255  0.762245   
1502  0.360566  0.851829  0.553591  0.790355  0.680031  0.672925  0.756026   
1503  0.365451  0.859877  0.554342  0.795695  0.681849  0.676648  0.761290   
1504  0.370859  0.855094  0.560413  0.792373  0.689080  0.670810  0.764065   

           Y_3       X_4       Y_4  ...      X_16      Y_16      X_17  \
0     0.267699  0.489235  0.159552  ...  0.553132  0.720161  0.330037   
1     0.277877  0.495069  0.174334  ...  0.560297  0.725905  0.333917   
2     0.271763  0.494588  0.166429  ...  0.563642  0.724375  0.329542   
3     0.267766  0.564681  0.151618  ...  0.556622  0.741055  0.232876   
4     0.274158  0.583863  0.159129  ...  0.567009  0.753000  0.236913   
...        ...       ...       ...  ...       ...       ...       ...   
1500  0.556774  0.851140  0.494178  ...  0.339253  0.190840  0.228042   
1501  0.558981  0.847888  0.497604  ...  0.331951  0.190506  0.221834   
1502  0.567728  0.846161  0.505885  ...  0.336357  0.188148  0.210512   
1503  0.571921  0.850647  0.511041  ...  0.348376  0.185799  0.214626   
1504  0.569512  0.852200  0.510579  ...  0.347795  0.186345  0.213344   

          Y_17      X_18      Y_18      X_19      Y_19      X_20      Y_20  
0     0.821747  0.242119  0.795591  0.390068  0.791163  0.484424  0.794198  
1     0.827795  0.256274  0.805499  0.414429  0.797631  0.504040  0.792535  
2     0.824363  0.259200  0.795218  0.410207  0.785890  0.500925  0.785399  
3     0.806132  0.270036  0.794235  0.428031  0.805391  0.489481  0.806653  
4     0.808531  0.278984  0.794343  0.432950  0.813703  0.487351  0.817951  
...        ...       ...       ...       ...       ...       ...       ...  
1500  0.533474  0.219571  0.429105  0.213487  0.362949  0.210716  0.304068  
1501  0.536412  0.214214  0.432144  0.206566  0.365390  0.199095  0.306208  
1502  0.532422  0.206585  0.425293  0.203183  0.358082  0.201975  0.298918  
1503  0.534448  0.214345  0.425949  0.211230  0.358164  0.208511  0.298078  
1504  0.539264  0.211028  0.429440  0.210004  0.359030  0.210458  0.296968  

[1505 rows x 42 columns]

In [26]:
# Split data 

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state = 47,shuffle=True)

print(X_train.shape,X_test.shape)
print(y_train.shape,y_test.shape)


(1053, 42) (452, 42)
(1053,) (452,)


In [ ]:
# Train Models
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB


forest_model = RandomForestClassifier()
SVC_model = SVC(kernel="linear",probability=True)
bayes_model = GaussianNB()

forest_model.fit(X_train,y_train)
SVC_model.fit(X_train,y_train)
bayes_model.fit(X_train,y_train)


GaussianNB()

In [28]:
# Evaluate model 
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

y_pred_forest = forest_model.predict(X_test)

acc_forest = accuracy_score(y_test,y_pred_forest)

print("Accuracy RD forest:{:.4f}".format(acc_forest))

class_report_forest = classification_report(y_test,y_pred_forest)
CF_matrix_forest = confusion_matrix(y_test,y_pred_forest)
print(class_report_forest)
print(CF_matrix_forest)

Accuracy RD forest:1.0000
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        97
           1       1.00      1.00      1.00        86
           2       1.00      1.00      1.00        95
           3       1.00      1.00      1.00        94
           4       1.00      1.00      1.00        80

    accuracy                           1.00       452
   macro avg       1.00      1.00      1.00       452
weighted avg       1.00      1.00      1.00       452

[[97  0  0  0  0]
 [ 0 86  0  0  0]
 [ 0  0 95  0  0]
 [ 0  0  0 94  0]
 [ 0  0  0  0 80]]


In [29]:
# Evaluate SVC model

y_pred_svc = SVC_model.predict(X_test)

acc_svc = accuracy_score(y_test,y_pred_svc)
print("Accuracy SVC: {:.4f}".format(acc_svc))

class_report_svc = classification_report(y_test,y_pred_svc)
CF_matrix_svc = confusion_matrix(y_test,y_pred_svc)
print(class_report_svc)
print(CF_matrix_svc)

Accuracy SVC: 1.0000
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        97
           1       1.00      1.00      1.00        86
           2       1.00      1.00      1.00        95
           3       1.00      1.00      1.00        94
           4       1.00      1.00      1.00        80

    accuracy                           1.00       452
   macro avg       1.00      1.00      1.00       452
weighted avg       1.00      1.00      1.00       452

[[97  0  0  0  0]
 [ 0 86  0  0  0]
 [ 0  0 95  0  0]
 [ 0  0  0 94  0]
 [ 0  0  0  0 80]]


In [30]:
# Evaluate NB model
y_pred_bayes = bayes_model.predict(X_test)

acc_bayes = accuracy_score(y_test,y_pred_bayes)
print("Accuracy NB: {:.4f}".format(acc_bayes))

class_report_bayes = classification_report(y_test,y_pred_bayes)
CF_mattrix_bayes = confusion_matrix(y_test,y_pred_bayes)
print(class_report_bayes)
print(CF_mattrix_bayes)


Accuracy NB: 0.9978
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        97
           1       1.00      0.99      0.99        86
           2       1.00      1.00      1.00        95
           3       1.00      1.00      1.00        94
           4       0.99      1.00      0.99        80

    accuracy                           1.00       452
   macro avg       1.00      1.00      1.00       452
weighted avg       1.00      1.00      1.00       452

[[97  0  0  0  0]
 [ 0 85  0  0  1]
 [ 0  0 95  0  0]
 [ 0  0  0 94  0]
 [ 0  0  0  0 80]]


In [31]:
# Save model 
import joblib

joblib.dump(forest_model,"forest_model.joblib")

['forest_model.joblib']

In [ ]:
# Save model 
import pickle 

#forest_model.save("C:/KMUTNB/Project_own/python/Project/hand_sign_classification/model_forest.h5")
f = open("/model_forest.pkl","wb")
pickle.dump(forest_model,f)
f.close()


In [33]:
df.columns

Index(['X_0', 'Y_0', 'X_1', 'Y_1', 'X_2', 'Y_2', 'X_3', 'Y_3', 'X_4', 'Y_4',
       'X_5', 'Y_5', 'X_6', 'Y_6', 'X_7', 'Y_7', 'X_8', 'Y_8', 'X_9', 'Y_9',
       'X_10', 'Y_10', 'X_11', 'Y_11', 'X_12', 'Y_12', 'X_13', 'Y_13', 'X_14',
       'Y_14', 'X_15', 'Y_15', 'X_16', 'Y_16', 'X_17', 'Y_17', 'X_18', 'Y_18',
       'X_19', 'Y_19', 'X_20', 'Y_20', 'Label'],
      dtype='object')